# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0014_materia_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='niv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materia.Grado'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
