# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('materia', '0016_userprofile_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grupos',
            field=models.ManyToManyField(to='usuario.UserGrupo'),
        ),
    ]
