# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0017_userprofile_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='temaProblema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=50)),
                ('resultado', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=50, null=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Temas')),
            ],
        ),
    ]
