# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materia', '0019_auto_20171113_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='proresuletos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='temaproblema',
            name='usa',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proresuletos',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.temaProblema'),
        ),
        migrations.AddField(
            model_name='proresuletos',
            name='use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
