# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0020_auto_20171113_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='proresuletos',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materia.Temas'),
        ),
    ]
