# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 23:46
from __future__ import unicode_literals

import apps.usuario.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to=apps.usuario.models.UserGrupo.url)),
                ('maestro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
